# Generated by Django 6.0.4 on 2026-04-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste image URL from Google/Imgur', null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='capacity',
            field=models.CharField(max_length=100),
        ),
    ]
