# Generated by Django 6.0.4 on 2026-05-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_machine_image_url_alter_machine_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='machine',
            field=models.CharField(max_length=200),
        ),
    ]
